version: '3.8'

volumes:
  mysql-data:

services:
  db:
    container_name: skkuting_db
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/postgresql/data
    environment:
      # NOTE: MYSQL_DB/USER/PASSWORD should match values in app container
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQLX_TCP_PORT: ${MYSQLX_TCP_PORT}
