debug: false
logging:
  level:
    skkumet.skkuting: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql: trace

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  sql.init.mode: always
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${username}
    password: ${password}
    properties:
      smtp.auth: true
      mail:
        smtp:
          starttls:
            enable: true
            required: true
    test-connection: true
  data:
    redis:
      port: 6379
      host: localhost


